/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;

public class App {

    public static void main(String[] args) {
        boolean shouldExit = true;
        // create the command line parser
        CommandLineParser parser = new DefaultParser();
        HelpFormatter helpFormatter = new HelpFormatter();
        // create the Options
        Options options = new Options();
        options.addOption("b", "batch <file>", false, "batch file containing expressions to evaluate");
        options.addOption("h", "help", false, "print usage message");
        options.addOption("o", "output <file>", false, "output file");

        try {
            CommandLine cmd = parser.parse(options, args);
            helpFormatter.printHelp("eval [OPTIONS]", "Evaluation of simple mathematical expressions.",
                    options, "1. Copyright (C) 2022 Savannah Webb".indent(15));
            if (shouldExit) {
                return;
            }
        } catch (ParseException exp) {
            System.err.println("Parsing failed. Reason: " + exp.getMessage());
        }
    }
}
